MVCcoreWebAppHTD1/Controllers/DDLController.cs
using Microsoft.AspNetCore.Mvc;
using MVCcoreWebAppHTD1.Models;
using MVCcoreWebAppHTD1.BusinessLogic_bl;
namespace MVCcoreWebAppHTD1.Controllers
{
    public class DDLController : Controller
    {
        [HttpGet]
        public IActionResult ViewDropDown()
        {
            ViewBag.data = ddl_bl.PopulateData();
            return View();
            
        }
        [HttpPost]
        public IActionResult ViewDropDown(string x)
        {
            ViewBag.data = Request.Form["test"].ToString() ;
            return View();

        }
        [HttpGet]
        public IActionResult GetDataonDDL()
        {

            ViewBag.data = ddl_bl.PopulateData();
            return View();
        }
        [HttpPost]
        public IActionResult GetDataonDDL(string x)
        {
            ViewData["Val"] = ddl_bl.GetOrdersByCust(Request.Form["test"].ToString());
            ViewBag.data = ddl_bl.PopulateData();
            return View();

        }

        [HttpGet]
        public IActionResult viewOrder()
        {
            ViewBag.data = ddl_bl.PopData();
            return View();

        }
        [HttpPost]
        public IActionResult vieworder(string x)
        {
            ViewBag.data = Request.Form["test"].ToString();
            return View();

        }
        [HttpGet]
        public IActionResult GetOrderDDL()
        {

            ViewBag.data = ddl_bl.PopData();
            return View();
        }
        [HttpPost]
        public IActionResult GetOrderDDL(string x)
        {
            //ViewData["Val"] = ddl_bl.GetdatByOrder (Request.Form["test"]);
            //ViewData["Value"] = ddl_bl.GetdatByOrder(Request.Form["demo"]);

            ViewBag.data = ddl_bl.PopData();
            return View();

        }
        [HttpGet]
        public IActionResult ViewCoun()
        {
            ViewBag.data = ddl_bl.Popcoun();
            return View();

        }
        [HttpPost]
        public IActionResult ViewCoun(string x)
        {
            ViewBag.data = Request.Form["test"].ToString();
            return View();

        }
        [HttpGet]
        public IActionResult GetCounonDDL()
        {

            ViewBag.data = ddl_bl.Popcoun();
            return View();
        }
        [HttpPost]
        public IActionResult GetCounonDDL(string x)
        {
            ViewData["Val"] = ddl_bl.GetCoun(Request.Form["test"].ToString());
            ViewBag.data = ddl_bl.Popcoun();
            return View();

        }
       
        [HttpGet]
        public IActionResult GetDataonShip()
        {

            ViewBag.data = ddl_bl.ShipData();
            return View();
        }
        [HttpPost]
        public IActionResult GetDataonShip(DateTime x)
        {
            ViewData["Val"] = ddl_bl.GetorderbyShip(Convert.ToDateTime(Request.Form["test"].ToString()));
            ViewBag.data = ddl_bl.ShipData();
            return View();
        
        }

    }


}

MVCcoreWebAppHTD1/Views/DDL/GetCounonDDL.cshtml
@{
    ViewData["Title"] = "GetCounonDDL";
    Layout = "~/Views/Shared/_userLayout.cshtml";
}

<h1>GetCounonDDL</h1>
@using (Html.BeginForm())
{
    if (ViewData["Val"] == null)
    {
        @Html.DropDownList("test", new SelectList(ViewBag.data, "ShipCountry", "ShipCountry"), "Please select", new { @id = "ddlFruits" })
        <input type="submit" value="submit" />
    }
    else
    {
       
        <table class="table table-striped">
            <tr>
                <th>OrderiD</th>
                <th>ShipCountry</th>
                <th>Emp ID</th>
                <th>Order Date</th>
                <th>Required Date</th>
                <th>Shipped Date</th>

 

            </tr>
            @foreach (var item in ViewData["Val"] as List<MVCcoreWebAppHTD1.Models.OrdersModel>)
            {
                <tr>
                    <td>@item.OrderID</td>
                    <td>@item.ShipCountry</td>
                    <td>@item.EmployeeID</td>
                    <td>@item.OrderDate</td>
                    <td>@item.RequiredDate</td>
                    <td>@item.ShippedDate</td>
                </tr>
            }
        </table>
    }
}

MVCcoreWebAppHTD1/Views/DDL/GetDataonDDL.cshtml
@{
    ViewData["Title"] = "GetDataonDDL";
    Layout = "~/Views/Shared/_userLayout.cshtml";
}

<h3>GetDataonDDL</h3>


@using (Html.BeginForm())
{
    if (ViewData["Val"] == null)
    {
        @Html.DropDownList("test", new SelectList(ViewBag.data, "CustomerID", "CustomerID"), "Please select", new { @id = "ddlFruits" })
        <input type="submit" value="submit" />
    }
    else
    {
       
        <table class="table table-striped">
            <tr>
                <th>OrderiD</th>
                <th>CustomerID</th>
                <th>Emp ID</th>
                <th>Order Date</th>
                <th>Required Date</th>
                <th>Shipped Date</th>

 

            </tr>
            @foreach (var item in ViewData["Val"] as List<MVCcoreWebAppHTD1.Models.OrdersModel>)
            {
                <tr>
                    <td>@item.OrderID</td>
                    <td>@item.CustomerID</td>
                    <td>@item.EmployeeID</td>
                    <td>@item.OrderDate</td>
                    <td>@item.RequiredDate</td>
                    <td>@item.ShippedDate</td>
                </tr>
            }
        </table>
    }
}

MVCcoreWebAppHTD1/Views/DDL/GetDataonShip.cshtml
@{
    ViewData["Title"] = "GetDataonShip";
    Layout = "~/Views/Shared/_userLayout.cshtml";
}

<h1>GetDataonShip</h1>

@using (Html.BeginForm())
{
    if (ViewData["Val"] == null)
    {
        @Html.DropDownList("test", new SelectList(ViewBag.data, "ShippedDate", "ShippedDate"), "Please select", new { @id = "ddlFruits" })
        <input type="submit" value="submit" />
    }
    else
    {
         @Html.DropDownList("test", new SelectList(ViewBag.data, "ShippedDate", "ShippedDate"), "Please select", new { @id = "ddlFruits" })
        <input type="submit" value="submit" />
       
        <table class="table table-striped">
            <tr>
                <th>OrderiD</th>
                <th>CustomerID</th>
                <th>Emp ID</th>
                <th>Order Date</th>
                <th>Required Date</th>   
                <th>Shipped Date</th>   
                <th>Ship Via </th>   
                <th>Ship Name </th>   
                <th>ShipCity </th>   
                <th>ShipCountry </th>   
               

 

            </tr>
            @foreach (var item in ViewData["Val"] as List<MVCcoreWebAppHTD1.Models.OrdersModel>)
            {
                <tr>
                    <td>@item.OrderID</td>
                    <td>@item.CustomerID</td>
                    <td>@item.EmployeeID</td>
                    <td>@item.OrderDate</td>
                    <td>@item.RequiredDate</td>
                    <td>@item.ShippedDate</td>
                    <td>@item.ShipVia</td>
                    <td>@item.ShipName</td>
                    <td>@item.ShipCity</td>
                    <td>@item.ShipCountry</td>
                </tr>
            }
        </table>
    }
}

MVCcoreWebAppHTD1/Views/DDL/GetOrderDDL.cshtml
@{
    ViewData["Title"] = "GetOrderDDL";
    Layout = "~/Views/Shared/_userLayout.cshtml";
}

<h1>GetOrderDDL</h1>

@using (Html.BeginForm())
{
    if (ViewData["Value"] == null)
    {
        @Html.DropDownList("test", new SelectList(ViewBag.data,"OrderDate","OrderDate"), "Please select", new { @id = "ddlFruits" })
        @Html.DropDownList("demo",new SelectList(ViewBag.data,"OrderDate","OrderDate"),"please select",new{@id="ddlfruits"})

        <input type="submit" value="submit" />
    }
    else
    {
       
        <table class="table table-striped">
            <tr>
                <th>OrderiD</th>
                <th>CustomerID</th>
                <th>Emp ID</th>
                <th>Required Date</th>
                <th>Shipped Date</th>
            </tr>
            @foreach (var item in ViewData["Val"] as List<MVCcoreWebAppHTD1.Models.OrdersModel>)
            {
                <tr>
                    <td>@item.OrderID</td>
                    <td>@item.CustomerID</td>
                    <td>@item.EmployeeID</td>
                    <td>@item.RequiredDate</td>
                    <td>@item.ShippedDate</td>
                </tr>
            }
        </table>
    }
}
}

MVCcoreWebAppHTD1/Views/DDL/ViewCoun.cshtml
@{
    ViewData["Title"] = "ViewCoun";
    Layout = "~/Views/Shared/_userLayout.cshtml";
}

<h1>ViewCoun</h1>

@Html.BeginForm("ViewCoun","DDL",FormMethod.Post)
{
@Html.DropDownList("test",new SelectList(ViewBag.data,"ShipCountry","ShipCountry"),"please select",new{@id="ddlfruits"})
<input type="submit" value="submit"/>

}

MVCcoreWebAppHTD1/Views/DDL/ViewDropDown.cshtml
@{
    ViewData["Title"] = "ViewDropDown";
    Layout = "~/Views/Shared/_userLayout.cshtml";
}

<h1>ViewDropDown</h1>

@Html.BeginForm("ViewDropDown","DDL",FormMethod.Post)
{
@Html.DropDownList("test",new SelectList(ViewBag.data,"CustomerID","CustomerID"),"please select",new{@id="ddlfruits"})
<input type="submit" value="submit"/>

}

MVCcoreWebAppHTD1/Views/DDL/vieworder.cshtml
@{
    ViewData["Title"] = "vieworder";
    Layout = "~/Views/Shared/_userLayout.cshtml";
}

<h1>vieworder</h1>

@Html.BeginForm("ViewDropDown","DDL",FormMethod.Post)
{
    
@Html.DropDownList("test",new SelectList(ViewBag.data,"OrderDate","OrderDate"),"please select",new{@id="ddlfruits"})
@Html.DropDownList("demo",new SelectList(ViewBag.data,"OrderDate","OrderDate"),"please select",new{@id="ddlfruits"})

<input type="submit" value="submit"/>

MVCcoreWebAppHTD1/Views/DDL/viewship.cshtml
@{
    ViewData["Title"] = "viewship";
    Layout = "~/Views/Shared/_userLayout.cshtml";
}

<h1>viewship</h1>

@Html.BeginForm("viewship","DDL",FormMethod.Post)
{
    
@Html.DropDownList("test",new SelectList(ViewBag.data,"ShippedDate","ShippedDate"),"please select",new{@id="ddlfruits"})


<input type="submit" value="submit"/>
}