MVCcoreWebAppHTD1/Controllers/FileUploadController.cs
using Microsoft.AspNetCore.Mvc;
using MVCcoreWebAppHTD1.Models;
using MVCcoreWebAppHTD1.BusinessLogic_bl;
using System.Data;
using System.Net;
using System.Net.Mail;
using System.IO;
using System.Data.SqlClient;
namespace MVCcoreWebAppHTD1.Controllers
{
    public class FileUploadController : Controller
    {
        [HttpGet]
        public IActionResult Upload()
        {
            return View(PopulateFiles());
        }

        [HttpPost]
        public IActionResult Upload(List<IFormFile> PostedFiles)
        {
            foreach (IFormFile PostedFile in PostedFiles)
            {
                string fileName = Path.GetFileName(PostedFile.FileName);
                string type = PostedFile.ContentType;
                byte[] bytes = null;
                using (MemoryStream ms = new MemoryStream())
                {
                    PostedFile.CopyTo(ms);
                    bytes = ms.ToArray();
                }
                var dbconfig = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json").Build();
                string dbconnectionstr = dbconfig["ConnectionStrings:DefaultConnection"];
                using (SqlConnection con = new SqlConnection(dbconnectionstr))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        cmd.CommandText = "insert into tbl_FileUploadDetails values (@Name,@ContentType,@Data)";
                        cmd.Parameters.AddWithValue("@Name", fileName);
                        cmd.Parameters.AddWithValue("@ContentType", type);
                        cmd.Parameters.AddWithValue("@Data", bytes);
                        cmd.Connection = con;
                        con.Open();
                        cmd.ExecuteNonQuery();
                        con.Close();
                    }
                }

            }
            return View(PopulateFiles());
        }

        public FileResult DownloadFile(int fileId)
        {
            FileUploadModel model = PopulateFiles().Find(model => model.ID == Convert.ToInt32(fileId));
            string fileName = model.Name;
            string contentType = model.ContentType;
            byte[] bytes = model.Data;
            return File(bytes, contentType, fileName);

        }

        public static List<FileUploadModel> PopulateFiles()
        {
            List<FileUploadModel> Files = new List<FileUploadModel>();
            var dbconfig = new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json").Build();
            string dbconnectionstr = dbconfig["ConnectionStrings:DefaultConnection"];
            using (SqlConnection con = new SqlConnection(dbconnectionstr))
            {
                string query = "select * from tbl_FileUploadDetails";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            Files.Add(new FileUploadModel
                            {
                                ID = Convert.ToInt32(sdr["ID"].ToString()),
                                Name = sdr["Name"].ToString(),
                                ContentType = sdr["ContentType"].ToString(),
                                Data = (byte[])sdr["Data"]
                            });
                        }
                    }
                    con.Close();
                }
            }

            return Files;
        }
        public IActionResult Delete(int fileId)
        {
            bool res = Files_bl.Delete(fileId);

            {
                return RedirectToAction("Upload");
            }

        }
    }

}

MVCcoreWebAppHTD1/Views/FileUpload/Delete.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
</body>
</html>

MVCcoreWebAppHTD1/Views/FileUpload/Upload.cshtml
@model IEnumerable<MVCcoreWebAppHTD1.Models.FileUploadModel>
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
    @using (Html.BeginForm("Upload", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <span>Select File:</span>
            <input type="file" name="PostedFiles" multiple />
        <input type="submit" value="Upload" />
        
    <hr />
       

    <table cellpadding="5" cellspacing="5">
        <tr>
            <th>Name</th>
            <th>Action</th>
        </tr>
        @foreach (FileUploadModel File in Model)
        {
            <tr>
                    <td>@File.Name</td>
                    <td>@*<a href="@Url.Action("DownloadFile","FileUpload", new { fileId = File.ID })">Download</a>*@
                        <a asp-action="DownloadFile" asp-route-fileId="@File.ID"><i class="text-sucess"><i class="fa fa-download fa-lg btn-sm ;"></i></a>
                      @* <a href="@Url.Action("Delete","FileUpload", new { fileId = File.ID })">Delete</a>*@
                        <a asp-action="Delete" asp-route-fileId="@File.ID"><i class="text-danger"><i class="fa fa-trash fa-lg btn-sm ;"></i></a>
                       </td>
            </tr> 
        }
    </table>
   }
</body>
</html>